### ISSUE TITLE
Issue with identifying protein-triggers

### ISSUE THREAD

**Issue by stripathy** [renaud/neuroNER#11]
Why is parvalbumin, calbindin and calretinin not recognized as part of the neuroNER below in the last part of the sentence (see image)? I think it has to do with the updating of the protein-trigger.

![screen shot 2015-06-16 at 9 26 05 am](https://cloud.githubusercontent.com/assets/2458713/8188326/0cdd2a00-140a-11e5-8de3-4eba6984e1e6.png)

Sentence: In doing so, we find that the vast majority (87%) of parvalbumin-immunoreactive neurons express m1-type muscarinic Acetylcholine receptors. m1 receptors are also expressed by 60% of calbindin-immunoreactive neurons and 40% of calretinin-immunoreactive neurons. m2 AChRs, on the other hand, are expressed by only 31% of parvalbumin neurons, 23% of calbindin neurons, and 25% of calretinin neurons.

**Comment by stripathy** [comment]
In other words, don't require that the protein trigger be activated before identifying the protein.

Parvalbumin-expressing neurons // works currently
parvalbumin neuron // doesn't work currently

neuron expressing parvalbumin // marks, but doesn't get ontology ID currently
// [NeuronTrigger] [ProteinTrigger] [ProteinProp]

**Comment by stripathy** [comment]
In addition to this case listed above:
parvalbumin neuron // doesn't work currently
//[ProteinProp] [NeuronTrigger]

We also need to support the following case:
parvalbumin basket cell
//[ProteinProp][NeuronProp][NeuronTrigger]

**Comment by renaud** [comment]
Should be fixed with [0d72d1f455](https://github.com/sherlok/sherlok/commit/0d72d1f4555bf7f9a5565ac8618c79004e37c171). Works for the following cases, see the tests
- parvalbumin basket cell
- Parvalbumin-expressing neurons
- neuron expressing parvalbumin
