### ISSUE TITLE
how does sherlok find resources?

### ISSUE THREAD

**Issue by stripathy** [renaud/neuroNER#14]
I edited the species.csv file, to remove PV as a species: 81a704809b192521bd11dd43a909bd681235bd91

But PV is still recognized as a species in the new Sherlok release. Why is this?

![screenshot from 2015-06-25 09 57 11](https://cloud.githubusercontent.com/assets/2458713/8360285/b176c298-1b20-11e5-8a54-fd5aeb3f9f7d.png)

**Comment by renaud** [comment]
if you edit remote resources, you need to reload the local ones with 

```
curl -X DELETE http://localhost:9600/clean/runtime_resources
```

(see https://github.com/sherlok/sherlok/wiki/Developing-a-text-mining-system-with-Sherlok#development-cycle)

does it work for you?
