### ISSUE TITLE
comparing neurolex to bbp and quantifying complete and partial overlap

### ISSUE THREAD

**Issue by stripathy** [renaud/neuroNER#27]
1. come up with two examples, something like a bipartite graph illustrating correspondence between neurolex and BBP, choose examples well.
2. statistics: how many terms in bbp exactly match a neurolex term, match but missing a term (like nest), etc.
3. literature comparison: 
   neocortex nest basket cell : term frequency
   nest basket cell
   basket cell
   nest cell
   neocortex basket cell
   ...

**Comment by stripathy** [comment]
Schematic of correspondence between neurolex and BBP (A and B). C is an example showing that even BBP cell types are insufficient to fully describe some of the things in the literature, illustrating the need for a compositional feature approach.

![normalization_schematic_v2](https://cloud.githubusercontent.com/assets/2458713/9030031/830a83b4-3951-11e5-94e2-ac771c0ee3af.png)

Below is a histogram contrasting the number of missing terms per BBP entity when compared to neurolex neuron types. See this ipython notebook for code: https://www.dropbox.com/s/eyok1abbup4rfbd/neurolex_bbp_ontology_compare.ipynb?dl=0

![neurolex_bbp_histo](https://cloud.githubusercontent.com/assets/2458713/9030064/f2df89c8-3951-11e5-8b9a-5ef4c9e0038b.png)

@renaud Can you do the literature comparison for a few terms?

**Comment by renaud** [comment]
Excellent, thanks a lot!

Yes, I will do the literature comparison if you don't have time.
