### ISSUE TITLE
possible duplicate terms for layer unions

### ISSUE THREAD

**Issue by stripathy** [renaud/neuroNER#29]
are these two not equivalent? I think that they are.

from here: https://github.com/renaud/neuroNER/blob/master/resources/bluima/neuroner/hbp_layer_ontology.obo

[Term]
id: HBP_LAYER:0000141
name: layer 5-6
synonym: "layer V-VI"  EXACT ALTERNATE_SPELLING []
synonym: "layer VI-V"  EXACT ALTERNATE_SPELLING [] ! unlikely
synonym: "layer 6-5"   EXACT ALTERNATE_SPELLING [] ! unlikely
synonym: "layers 5-6"  EXACT PLURAL []
synonym: "layers V-VI" EXACT ALTERNATE_PLURAL_SPELLING []
union_of: HBP_LAYER:0000005
union_of: HBP_LAYER:0000006

and

[Term]
id: HBP_LAYER:0000205
name: layer 5/6
synonym: "layer V/VI"  EXACT ALTERNATE_SPELLING []
synonym: "layers 5/6"  EXACT PLURAL []
synonym: "layers V/VI" EXACT ALTERNATE_PLURAL_SPELLING []
union_of: HBP_LAYER:0000005
union_of: HBP_LAYER:0000006

**Comment by renaud** [comment]
agreed, my bad

**Comment by stripathy** [comment]
fixed in ebe03fe8c0b7e384cf9837bf86d772cca14acc20
