### ISSUE TITLE
issue with identifying protein names

### ISSUE THREAD

**Issue by stripathy** [renaud/neuroNER#34]
Given the following .obo for a protein:

``` [Term]
id: NCBI_GENE:14811
name: Grin2a
synonym: "Glutamate receptor ionotropic, NMDA 2A" RELATED ADJECTIVE []
synonym: "NR2A" RELATED ADJECTIVE []
synonym: "Glutamate [NMDA] receptor subunit epsilon-1" RELATED ADJECTIVE []
synonym: "GluN2A" RELATED ADJECTIVE []
synonym: "Grin2a" RELATED ADJECTIVE []
synonym: "N-methyl D-aspartate receptor subtype 2A" RELATED ADJECTIVE []
synonym: "NMDAR2A" RELATED ADJECTIVE []
synonym: "Glutamate [NMDA] receptor subunit ε-1" RELATED ADJECTIVE []
```

The query: `'Grin2a-expressing neuron'` does not have a ProteinProp:
`[(18, 24, 'neuron', u'Neuron', {}), (18, 24, 'neuron', u'NeuronTrigger', {}), (7, 17, 'expressing', u'ProteinTrigger', {})]`

but `'NMDAR2A-expressing neuron'` has a ProteinProp:
`[(0, 25, 'NMDAR2A-expressing neuron', u'Neuron', {}), (19, 25, 'neuron', u'Neuron', {}), (8, 18, 'expressing', u'ProteinTrigger', {}), (0, 18, 'NMDAR2A-expressing', u'PreNeuron', {}), (0, 18, 'NMDAR2A-expressing', u'ProteinProp', {u'ontologyId': u'NCBI_GENE:14811'}), (19, 25, 'neuron', u'NeuronTrigger', {})]`

but `'GluN2A-expressing neuron'` doesn't have a ProteinProp but has a NeurotransmitterProp:
`[(0, 3, 'Glu', u'NeurotransmitterProp', {u'ontologyId': u'HBP_NEUROTRANSMITTER:0000004'}), (18, 24, 'neuron', u'Neuron', {}), (18, 24, 'neuron', u'NeuronTrigger', {}), (7, 17, 'expressing', u'ProteinTrigger', {})]`

**Comment by renaud** [comment]
I'm on it, I think I found an issue in Ruta and fixed it yesterday

**Comment by renaud** [comment]
i created a test with `Grin2a-expressing neuron space NMDAR2A-expressing neuron space GluN2A-expressing neuron`

```
{
  "ProteinProp": [
    {
      "begin": 0,
      "end": 17,
      "properties": {
        "ontologyId": "NCBI_GENE:14811"
      }
    },
    {
      "begin": 31,
      "end": 49,
      "properties": {
        "ontologyId": "NCBI_GENE:14811"
      }
    },
    {
      "begin": 63,
      "end": 80,
      "properties": {
        "ontologyId": "NCBI_GENE:14811"
      }
    }
  ],
  "Neuron": [
    {
      "begin": 0,
      "end": 24
    },
    {
      "begin": 31,
      "end": 56
    },
    {
      "begin": 63,
      "end": 87
    }
  ]
}
```
