### ISSUE TITLE
export uberon structure name as exact synonym .obo file

### ISSUE THREAD

**Issue by stripathy** [renaud/neuroNER#59]
@tgbugs I noticed the following:

> UBERON:0000411      visual cortex
> MBA:669             Visual areas
> ------ABA  SYNS------
> VIS
> Visual areas
> visual areas
> visual cortex
> -----UBERON SYNS-----
> --Related--
> higher-order visual cortex
> visual areas

but in the .obo files you prepared for me:

> [Term]
> id: ABA_REGION:669
> name: Visual areas
> synonym: "higher-order visual cortex" RELATED []
> synonym: "visual areas" RELATED []

In other words, we need to explicitly export the Uberon term name as an exact synonym (in the above example, visual cortex) when we're doing the conversion to .obo for parsing by neuroNER/sherlok

**Comment by tgbugs** [comment]
Ah yep, I'll add it.

**Comment by tgbugs** [comment]
@stripathy done via 4f07c5c3cc4e3bdbef1d6854f98da31bcde2ec27, note that sometimes this results in duplicate synonyms but that should be ok.

**Comment by tgbugs** [comment]
Do this with the the brain slim.

**Comment by tgbugs** [comment]
@stripathy files are here https://github.com/renaud/neuroNER/blob/master/ontology_merge/ns_stripped_e.obo according to the usual naming pattern.
